import { Link } from "react-router-dom";
import "./Legal.css";

const RingLogo = ({ size = 28 }: { size?: number }) => (
  <svg width={size} height={size} viewBox="0 0 96 96" fill="none">
    <circle cx="48" cy="48" r="38" stroke="white" strokeWidth="5" strokeOpacity="0.08"/>
    <circle cx="48" cy="48" r="38" stroke="#FF6B00" strokeWidth="5" strokeLinecap="round"
      strokeDasharray="179" strokeDashoffset="45" transform="rotate(-90 48 48)"/>
    <text x="48" y="56" textAnchor="middle"
      fontFamily="-apple-system, 'SF Pro Rounded', sans-serif"
      fontSize="38" fontWeight="700" fill="white" letterSpacing="-1">G</text>
  </svg>
);

export default function Terms() {
  return (
    <div className="legal-page">
      <nav className="legal-nav">
        <Link to="/" className="legal-nav-logo">
          <RingLogo size={28} />
          Gramo
        </Link>
      </nav>

      <div className="legal-body">
        <p className="legal-eyebrow">Legal</p>
        <h1 className="legal-title">Terms of Service</h1>
        <p className="legal-date">Effective date: 25 May 2026</p>

        <div className="legal-section">
          <p>By downloading or using Gramo, you agree to be bound by these Terms of Service. Please read them carefully. If you do not agree, do not use the app.</p>
        </div>

        <div className="legal-section">
          <h2>1. The Service</h2>
          <p>Gramo is an AI-powered macro and nutrition tracking application for iPhone. The service allows you to log food, track macros, set nutrition targets, and interact with an AI assistant to receive nutrition estimates.</p>
        </div>

        <div className="legal-section">
          <h2>2. Not Medical Advice</h2>
          <p>Gramo is a general wellness and nutrition tracking tool. It is <strong style={{color:"rgba(245,245,247,0.8)"}}>not a medical service</strong> and does not provide medical advice, diagnosis, or treatment. Nutrition estimates generated by the AI are approximations and should not be relied upon for medical or clinical decisions.</p>
          <p>Always consult a qualified healthcare professional before making significant changes to your diet, especially if you have an existing medical condition.</p>
        </div>

        <div className="legal-section">
          <h2>3. Your Account</h2>
          <ul>
            <li>You must be at least 13 years old to use Gramo.</li>
            <li>You are responsible for maintaining the security of your account credentials.</li>
            <li>You are responsible for all activity that occurs under your account.</li>
            <li>You must provide accurate information during registration and keep it up to date.</li>
          </ul>
        </div>

        <div className="legal-section">
          <h2>4. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul>
            <li>Use the app for any unlawful purpose or in violation of any applicable law.</li>
            <li>Attempt to reverse-engineer, decompile, or extract the source code of Gramo.</li>
            <li>Abuse or overload the AI service in a way that degrades performance for other users.</li>
            <li>Submit content that is harmful, offensive, or violates the rights of others.</li>
            <li>Attempt to access another user's account or data.</li>
          </ul>
        </div>

        <div className="legal-section">
          <h2>5. AI-Generated Content</h2>
          <p>Nutrition estimates provided by Gramo's AI are generated automatically based on the information you provide. These estimates are approximate and may not be accurate for every food item, portion size, or preparation method. You acknowledge that:</p>
          <ul>
            <li>AI-generated nutrition data is not guaranteed to be accurate or complete.</li>
            <li>You use nutrition estimates at your own discretion and risk.</li>
            <li>Gramo is not liable for decisions made based on AI-generated estimates.</li>
          </ul>
        </div>

        <div className="legal-section">
          <h2>6. Subscription and Pricing</h2>
          <p>Gramo may offer free and paid tiers of service. Pricing, features, and availability of paid tiers will be disclosed clearly within the app before any purchase. All purchases are subject to Apple's App Store terms and are processed by Apple.</p>
        </div>

        <div className="legal-section">
          <h2>7. Intellectual Property</h2>
          <p>All content, design, code, and branding within Gramo is owned by or licensed to us and is protected by applicable intellectual property laws. You may not reproduce or redistribute any part of the app without our written permission.</p>
          <p>You retain ownership of the content you submit (food logs, photos, messages). By using the service, you grant us a limited licence to process that content solely to provide the service to you.</p>
        </div>

        <div className="legal-section">
          <h2>8. Termination</h2>
          <p>We reserve the right to suspend or terminate your access to Gramo at any time if you violate these Terms or if we discontinue the service. You may delete your account at any time from within the app.</p>
        </div>

        <div className="legal-section">
          <h2>9. Disclaimers and Limitation of Liability</h2>
          <p>Gramo is provided "as is" without warranties of any kind, express or implied. To the fullest extent permitted by law, we disclaim all liability for any indirect, incidental, special, or consequential damages arising from your use of the app, including inaccurate nutrition data or service interruptions.</p>
        </div>

        <div className="legal-section">
          <h2>10. Changes to These Terms</h2>
          <p>We may update these Terms from time to time. Continued use of Gramo after changes are posted constitutes your acceptance of the revised Terms. We will update the effective date above when changes are made.</p>
        </div>

        <div className="legal-section">
          <h2>11. Governing Law</h2>
          <p>These Terms are governed by the laws of Singapore, without regard to conflict of law principles.</p>
        </div>

        <div className="legal-contact-card">
          <h3>Questions?</h3>
          <p>If you have questions about these Terms, contact us at <a href="mailto:hello@gramo.space">hello@gramo.space</a>.</p>
        </div>
      </div>
    </div>
  );
}
